export const COLORS_MAP = {
  red: "red",
  orange: "orange",
  yellow: "yellow",
  lightgreen: "green",
  lightblue: "blue",
  pink: "pink",
  magenta: "purple", // *
  cyan: "turquoise", // *
  lightgray: "toolbar", // *
};

export const CONTEXTUAL_ICONS = [
  "fingerprint",
  "briefcase",
  "dollar",
  "cart",
  "circle",
  "gift",
  "vacation",
  "food",
  "fruit",
  "pet",
  "tree",
  "chill",
  "fence",
];

export const TELEMETRY_LIST = [
  "firefox-settings-attachments.cdn.mozilla.net",
  "detectportal.firefox.com",
  "contile.services.mozilla.com",
  "firefox.settings.services.mozilla.com",
  "classify-client.services.mozilla.com",
  "safebrowsing.googleapis.com",
  "www.google-analytics.com",
  "geller-pa.googleapis.com",
  "graph.facebook.com",
  "pubsub.googleapis.com",
  "www.googletagmanager.com",
  "content-autofill.googleapis.com",
  "www.googleapis.com",
  "pubsub.googleapis.com",
  "analytics.google.com",
  "googleads.g.doubleclick.net",
  "analytics.twitter.com",
  "analytics.tiktok.com",
  "fonts.googleapis.com",
  "adservice.google.com",
  "doubleclick.net",
  "bat.bing.com",
  "connect.facebook.net",
  "googletagmanager.com",
  "s.clarity.ms",
  "tr.snapchat.com",
  "s.amazon-adsystem.com",
  "sdk.split.io",
  "hotjar.io",
  "mixpanel.com",
  "hotjar.com",
  "i.ytimg.com",
  "ads.mozilla.org",
  "ads-img.mozilla.org",
  "versioncheck-bg.addons.mozilla.org",
  "services.addons.mozilla.org",
];
